version: '3.8'

services:
  auth_db:
    image: postgres:17.5-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: authentification-service
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: authentification-db
    ports:
      - "5444:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  vault:
    image: hashicorp/vault:latest
    container_name: dev-vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    command: server -dev
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: dev-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: auth_db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: authentification-db
      KC_DB_USERNAME: authentification-service
      KC_DB_PASSWORD: 1234
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - auth_db
    restart: always

volumes:
  auth_data:
    driver: local
